const actionTypes = {
    LANDING_PAGE_DATA_START: "LANDING_PAGE_DATA_START",
    LANDING_PAGE_DATA_SUCCEEDED: "LANDING_PAGE_DATA_SUCCEEDED",
    LANDING_PAGE_DATA_FAILED:"LANDING_PAGE_DATA_FAILED",

    //DEPLOY
    DEPLOY_PAGE_DATA_START: "DEPLOY_PAGE_DATA_START",
    DEPLOY_PAGE_DATA_SUCCEEDED: "DEPLOY_PAGE_DATA_SUCCEEDED",
    DEPLOY_PAGE_DATA_FAILED:"DEPLOY_PAGE_DATA_FAILED",
    CLEAR_ADD_CREDIT_CARD:"CLEAR_ADD_CREDIT_CARD",

    //EXPERTISE

    EXPERTISE_PAGE_DATA_START: "EXPERTISE_PAGE_DATA_START",
    EXPERTISE_PAGE_DATA_SUCCEEDED: "EXPERTISE_PAGE_DATA_SUCCEEDED",
    EXPERTISE_PAGE_DATA_FAILED:"EXPERTISE_PAGE_DATA_FAILED",

    //CASESTUDIES

    CASE_STUDIES_PAGE_DATA_START: "CASE_STUDIES_PAGE_DATA_START",
    CASE_STUDIES_DATA_SUCCEEDED: "CASE_STUDIES_DATA_SUCCEEDED",
    CASE_STUDIES_DATA_FAILED:"CASE_STUDIES_DATA_FAILED",

    //CAPTION

    CAPTION_PAGE_DATA_START:"CAPTION_PAGE_DATA_START",
    CAPTION_DATA_SUCCEEDED: "CAPTION_DATA_SUCCEEDED",
    CAPTION_DATA_FAILED:"CAPTION_DATA_FAILED",

    //NEWSROOM

    NEWS_ROOM_PAGE_DATA_START:"NEWS_ROOM_PAGE_DATA_START",
    NEWS_ROOM_DATA_SUCCEEDED: "NEWS_ROOM_DATA_SUCCEEDED",
    NEWS_ROOM_DATA_FAILED:"NEWS_ROOM_DATA_FAILED",

    //HISTORY

    HISTORY_PAGE_DATA_START:"HISTORY_PAGE_DATA_START",
    HISTORY_DATA_SUCCEEDED: "HISTORY_DATA_SUCCEEDED",
    HISTORY_DATA_FAILED:"HISTORY_DATA_FAILED",

    //GETINTOUCH
     
    GET_IN_TOUCH_PAGE_DATA_START:"GET_IN_TOUCH_PAGE_DATA_START",
    GET_IN_TOUCH_DATA_SUCCEEDED: "GET_IN_TOUCH_DATA_SUCCEEDED",
    GET_IN_TOUCH_DATA_FAILED:"GET_IN_TOUCH_DATA_FAILED",
    


    //ABOUT PAGE STARTS
  

    //UVATION

    UVATION_PAGE_DATA_START:"UVATION_PAGE_DATA_START",
    UVATION_DATA_SUCCEEDED: "UVATION_DATA_SUCCEEDED",
    UVATION_DATA_FAILED:"UVATION_DATA_FAILED",

    //COMPANY
    COMPANY_PAGE_DATA_START:"COMPANY_PAGE_DATA_START",
    COMPANY_DATA_SUCCEEDED: "COMPANY_DATA_SUCCEEDED",
    COMPANY_DATA_FAILED:"COMPANY_DATA_FAILED",

    //BRAND 

    BRAND_PAGE_DATA_START:"BRAND_PAGE_DATA_START",
    BRAND_DATA_SUCCEEDED: "BRAND_DATA_SUCCEEDED",
    BRAND_DATA_FAILED:"BRAND_DATA_FAILED",

    //SERVICE

    SERVICE_PAGE_DATA_START:"SERVICE_DATA_START",
    SERVICE_DATA_SUCCEEDED: "SERVICE_DATA_SUCCEEDED",
    SERVICE_DATA_FAILED:"SERVICE_DATA_FAILED",

    //PEOPLE

    PEOPLE_PAGE_DATA_START:"PEOPLE_PAGE_DATA_START",
    PEOPLE_DATA_SUCCEEDED: "PEOPLE_DATA_SUCCEEDED",
    PEOPLE_DATA_FAILED:"PEOPLE_DATA_FAILED",

    //HISTORY
     
    ABOUT_HISTORY_PAGE_DATA_START:"ABOUT_HISTORY_PAGE_DATA_START",
    ABOUT_HISTORY_DATA_SUCCEEDED: "ABOUT_HISTORY_DATA_SUCCEEDED",
    ABOUT_HISTORY_DATA_FAILED:"ABOUT_HISTORY_DATA_FAILED",

    //ABOUT PAGE ENDS


    //CONTACT US PAGE STARTS

    //REACHUS

    REACH_US_PAGE_DATA_START:"REACH_US_PAGE_DATA_START",
    REACH_US_DATA_SUCCEEDED: "REACH_US_DATA_SUCCEEDED",
    REACH_US_DATA_FAILED:"REACH_US_DATA_FAILED",

    //MORECONTACTUS

    MORE_CONTACT_US_PAGE_DATA_START:"MORE_CONTACT_US_PAGE_DATA_START",
    MORE_CONTACT_US_DATA_SUCCEEDED: "MORE_CONTACT_US_DATA_SUCCEEDED",
    MORE_CONTACT_US_DATA_FAILED:"MORE_CONTACT_US_DATA_FAILED",

    //CONTACT US PAGE ENDS

    //INDUSTRIES PAGE STARTS

    //INDUSTRIES

    INDUSTRIES_PAGE_DATA_START:"INDUSTRIES_PAGE_DATA_START",
    INDUSTRIES_DATA_SUCCEEDED: "INDUSTRIES_DATA_SUCCEEDED",
    INDUSTRIES_DATA_FAILED:"INDUSTRIES_DATA_FAILED",

    //FEATURED

    FEATURED_PAGE_DATA_START:"FEATURED_PAGE_DATA_START",
    FEATURED_DATA_SUCCEEDED: "FEATURED_DATA_SUCCEEDED",
    FEATURED_DATA_FAILED:"FEATURED_DATA_FAILED",

    //FUTURE INDUSTRIES

    FUTURE_INDUSTRIES_PAGE_DATA_START:"FUTURE_INDUSTRIES_PAGE_DATA_START",
    FUTURE_INDUSTRIES_DATA_SUCCEEDED: "FUTURE_INDUSTRIES_DATA_SUCCEEDED",
    FUTURE_INDUSTRIES_DATA_FAILED:"FUTURE_INDUSTRIES_DATA_FAILED",

    //WORK WITH

    WORK_WITH_PAGE_DATA_START:"WORK_WITH_PAGE_DATA_START",
    WORK_WITH_DATA_SUCCEEDED: "WORK_WITH_DATA_SUCCEEDED",
    WORK_WITH_DATA_FAILED:"WORK_WITH_DATA_FAILED",

    //RESOURCES

    RESOURCES_PAGE_DATA_START:"RESOURCES_PAGE_DATA_START",
    RESOURCES_DATA_SUCCEEDED: "RESOURCES_DATA_SUCCEEDED",
    RESOURCES_DATA_FAILED:"RESOURCES_DATA_FAILED",

    //EXPLORE

    EXPLORE_PAGE_DATA_START:"EXPLORE_PAGE_DATA_START",
    EXPLORE_DATA_SUCCEEDED: "EXPLORE_DATA_SUCCEEDED",
    EXPLORE_DATA_FAILED:"EXPLORE_DATA_FAILED",

    //INDUSTRIES PAGE ENDS


    //INNOVATION PAGE STARTS

    //INNOVATION
    INNOVATION_PAGE_DATA_START:"INNOVATION_PAGE_DATA_START",
    INNOVATION_DATA_SUCCEEDED: "INNOVATION_DATA_SUCCEEDED",
    INNOVATION_DATA_FAILED:"INNOVATION_DATA_FAILED",

    //FEATURED INNOVATION

    FEATURED_INNOVATION_PAGE_DATA_START:"FEATURED_INNOVATION_PAGE_DATA_START",
    FEATURED_INNOVATION_DATA_SUCCEEDED: "FEATURED_INNOVATION_DATA_SUCCEEDED",
    FEATURED_INNOVATION_DATA_FAILED:"FEATURED_INNOVATION_DATA_FAILED",
    
    //RECOMMENDED
    RECOMMENDED_PAGE_DATA_START:"RECOMMENDED_PAGE_DATA_START",
    RECOMMENDED_DATA_SUCCEEDED: "RECOMMENDED_DATA_SUCCEEDED",
    RECOMMENDED_DATA_FAILED:"RECOMMENDED_DATA_FAILED",

    //CONTENT

    CONTENT_PAGE_DATA_START:"CONTENT_PAGE_DATA_START",
    CONTENT_DATA_SUCCEEDED: "CONTENT_DATA_SUCCEEDED",
    CONTENT_DATA_FAILED:"CONTENT_DATA_FAILED",
     
    //INNOVATION EXPLORE

    INNOVATION_EXPLORE_PAGE_DATA_START:"INNOVATION_EXPLORE_PAGE_DATA_START",
    INNOVATION_EXPLORE_DATA_SUCCEEDED: "INNOVATION_EXPLORE_DATA_SUCCEEDED",
    INNOVATION_EXPLORE_DATA_FAILED:"INNOVATION_EXPLORE_DATA_FAILED",
    
    //INNOVATION PAGE ENDS

    //CAREER PAGE STARTS

    //CAREER

    CAREER_PAGE_DATA_START:"CAREER_PAGE_DATA_START",
    CAREER_DATA_SUCCEEDED: "CAREER_DATA_SUCCEEDED",
    CAREER_DATA_FAILED:"CAREER_DATA_FAILED",

    //CAREER UVATION

    CAREER_UVATION_PAGE_DATA_START:"CAREER_UVATION_PAGE_DATA_START",
    CAREER_UVATION_DATA_SUCCEEDED: "CAREER_UVATION_DATA_SUCCEEDED",
    CAREER_UVATION_DATA_FAILED:"CAREER_UVATION_DATA_FAILED",

    //APPLYING

    APPLYING_PAGE_DATA_START:"APPLYING_PAGE_DATA_START",
    APPLYING_DATA_SUCCEEDED: "APPLYING_DATA_SUCCEEDED",
    APPLYING_DATA_FAILED:"APPLYING_DATA_FAILED",

    //JOB

    JOB_PAGE_DATA_START:"JOB_PAGE_DATA_START",
    JOB_DATA_SUCCEEDED: "JOB_DATA_SUCCEEDED",
    JOB_DATA_FAILED:"JOB_DATA_FAILED",

    //QUESTIONS

    QUESTIONS_PAGE_DATA_START:"QUESTIONS_PAGE_DATA_START",
    QUESTIONS_DATA_SUCCEEDED: "QUESTIONS_DATA_SUCCEEDED",
    QUESTIONS_DATA_FAILED:"QUESTIONS_DATA_FAILED",


    //CAREER PAGE ENDS

    //PARTNERSHIP PAGE starts
     
    //Partnership

    PARTNERSHIP_PAGE_DATA_START:"PARTNERSHIP_PAGE_DATA_START ",
    PARTNERSHIP_DATA_SUCCEEDED: "PARTNERSHIP_DATA_SUCCEEDED",
    PARTNERSHIP_DATA_FAILED:"PARTNERSHIP_DATA_FAILED",

    //DISCOVER

    DISCOVER_PAGE_DATA_START:"DISCOVER_PAGE_DATA_START",
    DISCOVER_DATA_SUCCEEDED: "DISCOVER_DATA_SUCCEEDED",
    DISCOVER_DATA_FAILED:"DISCOVER_DATA_FAILED",

    //CHANNEL

    CHANNEL_PAGE_DATA_START:"CHANNEL_PAGE_DATA_START",
    CHANNEL_DATA_SUCCEEDED: "CHANNEL_DATA_SUCCEEDED",
    CHANNEL_DATA_FAILED:"CHANNEL_DATA_FAILED",

    //PARTNERSHIP PAGE ENDS

    //PEOPLE PAGE DATA STARTS

    //PEOPLES
    PEOPLES_PAGE_DATA_START:"PEOPLES_PAGE_DATA_START",
    PEOPLES_DATA_SUCCEEDED: "PEOPLES_DATA_SUCCEEDED",
    PEOPLES_DATA_FAILED:"PEOPLES_DATA_FAILED",

    //TEAM PEOPLE

    TEAM_PEOPLE_PAGE_DATA_START:"TEAM_PEOPLE_PAGE_DATA_START",
    TEAM_PEOPLE_DATA_SUCCEEDED: "TEAM_PEOPLE_DATA_SUCCEEDED",
    TEAM_PEOPLE_DATA_FAILED:"TEAM_PEOPLE_DATA_FAILED",

    //PEOPLE PAGE DATA ENDS

//Investors Relations Page starts

//INFORMATION

INVESTOR_INFORMATION_PAGE_DATA_START:"INVESTOR_INFORMATION_PAGE_DATA_START",
INVESTOR_INFORMATION_DATA_SUCCEEDED: "INVESTOR_INFORMATION_DATA_SUCCEEDED",
INVESTOR_INFORMATION_DATA_FAILED:"INVESTOR_INFORMATION_DATA_FAILED",

//news

INVESTOR_NEWS_PAGE_DATA_START:"INVESTOR_NEWS_PAGE_DATA_START",
INVESTOR_NEWS_DATA_SUCCEEDED: "INVESTOR_NEWS_DATA_SUCCEEDED",
INVESTOR_NEWS_DATA_FAILED:"INVESTOR_NEWS_DATA_FAILED",

//UVATION

INVESTOR_UVATION_PAGE_DATA_START:"INVESTOR_UVATION_PAGE_DATA_START",
INVESTOR_UVATION_DATA_SUCCEEDED: "INVESTOR_UVATION_DATA_SUCCEEDED",
INVESTOR_UVATION_DATA_FAILED:"INVESTOR_UVATION_DATA_FAILED",

//WANT

INVESTOR_WANT_PAGE_DATA_START:"INVESTOR_WANT_PAGE_DATA_START",
INVESTOR_WANT_DATA_SUCCEEDED: "INVESTOR_WANT_DATA_SUCCEEDED",
INVESTOR_WANT_DATA_FAILED:"INVESTOR_WANT_DATA_FAILED",


//Investors Relations Page eNDS

//Investors Sla Page Starts

//heading

INVESTOR_HEADING_PAGE_DATA_START:"INVESTOR_HEADING_PAGE_DATA_START",
INVESTOR_HEADING_DATA_SUCCEEDED: "INVESTOR_HEADING_DATA_SUCCEEDED",
INVESTOR_HEADING_DATA_FAILED:"INVESTOR_HEADING_DATA_FAILED",


//Investors Sla Page Ends

//Technology Service Page Starts

//TechnologyHeading

TECHNOLOGY_HEADING_PAGE_DATA_START:"TECHNOLOGY_HEADING_PAGE_DATA_START",
TECHNOLOGY_HEADING_DATA_SUCCEEDED: "TECHNOLOGY_HEADING_DATA_SUCCEEDED",
TECHNOLOGY_HEADING_DATA_FAILED:"TECHNOLOGY_HEADING_DATA_FAILED",


//Technology Service Page Ends

//Application Page Starts

//application

APPLICATION_PAGE_DATA_START:"APPLICATION_PAGE_DATA_START",
APPLICATION_DATA_SUCCEEDED: "APPLICATION_DATA_SUCCEEDED",
APPLICATION_DATA_FAILED:"APPLICATION_DATA_FAILED",

//BENEFITS

BENEFITS_PAGE_DATA_START:"BENEFITS_PAGE_DATA_START",
BENEFITS_DATA_SUCCEEDED: "BENEFITS_DATA_SUCCEEDED",
BENEFITS_DATA_FAILED:"BENEFITS_DATA_FAILED",

//DEVELOP

DEVELOP_PAGE_DATA_START:"DEVELOP_PAGE_DATA_START",
DEVELOP_DATA_SUCCEEDED: "DEVELOP_DATA_SUCCEEDED",
DEVELOP_DATA_FAILED:"DEVELOP_DATA_FAILED",

//BUSINESS

BUSINESS_PAGE_DATA_START:"BUSINESS_PAGE_DATA_START",
BUSINESS_DATA_SUCCEEDED: "BUSINESS_DATA_SUCCEEDED",
BUSINESS_DATA_FAILED:"BUSINESS_DATA_FAILED",

//APPLICATION TABS

APPLICATION_TABS_PAGE_DATA_START:"APPLICATION_TABS_PAGE_DATA_START",
APPLICATION_TABS_DATA_SUCCEEDED: "APPLICATION_TABS_DATA_SUCCEEDED",
APPLICATION_TABS_DATA_FAILED:"APPLICATION_TABS_DATA_FAILED",

//APPLICATION CHAT

APPLICATION_CHAT_PAGE_DATA_START:"APPLICATION_CHAT_PAGE_DATA_START",
APPLICATION_CHAT_DATA_SUCCEEDED: "APPLICATION_CHAT_DATA_SUCCEEDED",
APPLICATION_CHAT_DATA_FAILED:"APPLICATION_CHAT_DATA_FAILED",

//Application Page Ends


//Business Resiliency Page Starts
 
BUSINESS_LANDING_PAGE_DATA_START:"BUSINESS_LANDING_PAGE_DATA_START",
BUSINESS_LANDING_DATA_SUCCEEDED: "BUSINESS_LANDING_DATA_SUCCEEDED",
BUSINESS_LANDING_DATA_FAILED:"BUSINESS_LANDING_DATA_FAILED",

//Resilency
 
RESILIENCY_PAGE_DATA_START:"RESILIENCY_PAGE_DATA_START",
RESILIENCY_DATA_SUCCEEDED: "RESILIENCY_DATA_SUCCEEDED",
RESILIENCY_DATA_FAILED:"RESILIENCY_DATA_FAILED",

//Improve

IMPROVE_PAGE_DATA_START:"IMPROVE_PAGE_DATA_START",
IMPROVE_DATA_SUCCEEDED: "IMPROVE_DATA_SUCCEEDED",
IMPROVE_DATA_FAILED:"IMPROVE_DATA_FAILED",

//Chat

BUSINESS_CHAT_PAGE_DATA_START:"BUSINESS_CHAT_PAGE_DATA_START",
BUSINESS_CHAT_DATA_SUCCEEDED: "BUSINESS_CHAT_DATA_SUCCEEDED",
BUSINESS_CHAT_DATA_FAILED:"BUSINESS_CHAT_DATA_FAILED",


//Business Resiliency Page Ends

//Cloud Page Starts

//CLOUD lANDING

CLOUD_LANDING_PAGE_DATA_START:"CLOUD_LANDING_PAGE_DATA_START",
CLOUD_LANDING_DATA_SUCCEEDED: "CLOUD_LANDING_DATA_SUCCEEDED",
CLOUD_LANDING_DATA_FAILED:"CLOUD_LANDING_DATA_FAILED",

//CLOUD BENIFITS

CLOUD_BENIFITS_PAGE_DATA_START:"CLOUD_BENIFITS_PAGE_DATA_START",
CLOUD_BENIFITS_DATA_SUCCEEDED: "CLOUD_BENIFITS_DATA_SUCCEEDED",
CLOUD_BENIFITS_DATA_FAILED:"CLOUD_BENIFITS_DATA_FAILED",

//CLOUD GET

CLOUD_GET_PAGE_DATA_START:"CLOUD_GET_PAGE_DATA_START",
CLOUD_GET_DATA_SUCCEEDED: "CLOUD_GET_DATA_SUCCEEDED",
CLOUD_GET_DATA_FAILED:"CLOUD_GET_DATA_FAILED",

//CLOUD COMPUTING

CLOUD_COMPUTING_PAGE_DATA_START:"CLOUD_COMPUTING_PAGE_DATA_START",
CLOUD_COMPUTING_DATA_SUCCEEDED: "CLOUD_COMPUTING_DATA_SUCCEEDED",
CLOUD_COMPUTING_DATA_FAILED:"CLOUD_COMPUTING_DATA_FAILED",

//CLOUD UNIQUE

CLOUD_UNIQUE_PAGE_DATA_START:"CLOUD_UNIQUE_PAGE_DATA_START",
CLOUD_UNIQUE_DATA_SUCCEEDED: "CLOUD_UNIQUE_DATA_SUCCEEDED",
CLOUD_UNIQUE_DATA_FAILED:"CLOUD_UNIQUE_DATA_FAILED",

//CLOUD DIFFERENT

CLOUD_DIFFERENT_PAGE_DATA_START:"CLOUD_DIFFERENT_PAGE_DATA_START",
CLOUD_DIFFERENT_DATA_SUCCEEDED: "CLOUD_DIFFERENT_DATA_SUCCEEDED",
CLOUD_DIFFERENT_DATA_FAILED:"CLOUD_DIFFERENT_DATA_FAILED",

//CLOUD CHAT

CLOUD_CHAT_PAGE_DATA_START:"CLOUD_CHAT_PAGE_DATA_START",
CLOUD_CHAT_DATA_SUCCEEDED: "CLOUD_CHAT_DATA_SUCCEEDED",
CLOUD_CHAT_DATA_FAILED:"CLOUD_CHAT_DATA_FAILED",


//Cloud Page Ends

//Data Center Page Starts

//CENTERLANDING

CENTER_LANDING_PAGE_DATA_START:"CENTER_LANDING_PAGE_DATA_START",
CENTER_LANDING_DATA_SUCCEEDED: "CENTER_LANDING_DATA_SUCCEEDED",
CENTER_LANDING_DATA_FAILED:"CENTER_LANDING_DATA_FAILED",

//Center Benifits

CENTER_BENIFITS_PAGE_DATA_START:"CENTER_BENIFITS_PAGE_DATA_START",
CENTER_BENIFITS_DATA_SUCCEEDED: "CENTER_BENIFITS_DATA_SUCCEEDED",
CENTER_BENIFITS_DATA_FAILED:"CENTER_BENIFITS_DATA_FAILED",

//Center Deploy

CENTER_DEPLOY_PAGE_DATA_START:"CENTER_DEPLOY_PAGE_DATA_START",
CENTER_DEPLOY_DATA_SUCCEEDED: "CENTER_DEPLOY_DATA_SUCCEEDED",
CENTER_DEPLOY_DATA_FAILED:"CENTER_DEPLOY_DATA_FAILED",

//Center Explained
CENTER_EXPLAINED_PAGE_DATA_START:"CENTER_EXPLAINED_PAGE_DATA_START",
CENTER_EXPLAINED_DATA_SUCCEEDED: "CENTER_EXPLAINED_DATA_SUCCEEDED",
CENTER_EXPLAINED_DATA_FAILED:"CENTER_EXPLAINED_DATA_FAILED",

//Center Services

CENTER_SERVICES_PAGE_DATA_START:"CENTER_SERVICES_PAGE_DATA_START",
CENTER_SERVICES_DATA_SUCCEEDED: "CENTER_SERVICES_DATA_SUCCEEDED",
CENTER_SERVICES_DATA_FAILED:"CENTER_SERVICES_DATA_FAILED",

// CENTER TECHNOLOGIES

CENTER_TECHNOLOGIES_PAGE_DATA_START:"CENTER_TECHNOLOGIES_PAGE_DATA_START",
CENTER_TECHNOLOGIES_DATA_SUCCEEDED: "CENTER_TECHNOLOGIES_DATA_SUCCEEDED",
CENTER_TECHNOLOGIES_DATA_FAILED:"CENTER_TECHNOLOGIES_DATA_FAILED",

// CENTER CHAT

CENTER_CHAT_PAGE_DATA_START:"CENTER_CHAT_PAGE_DATA_START ",
CENTER_CHAT_DATA_SUCCEEDED: "CENTER_CHAT_DATA_SUCCEEDED",
CENTER_CHAT_DATA_FAILED:"CENTER_CHAT_DATA_FAILED",

//DATA CENTER PAGE ENDS

//MANAGED IT PAGE STARTS


//MANAGEDIT LANDING

MANAGEDIT_LANDING_PAGE_DATA_START:"MANAGEDIT_LANDING_PAGE_DATA_START",
MANAGEDIT_LANDING_DATA_SUCCEEDED: "MANAGEDIT_LANDING_DATA_SUCCEEDED",
MANAGEDIT_LANDING_DATA_FAILED:"MANAGEDIT_LANDING_DATA_FAILED",

//MANAGEDIT BENEFITS
MANAGEDIT_BENEFITS_PAGE_DATA_START:"MANAGEDIT_BENEFITS_PAGE_DATA_START",
MANAGEDIT_BENEFITS_DATA_SUCCEEDED: "MANAGEDIT_BENEFITS_DATA_SUCCEEDED",
MANAGEDIT_BENEFITS_DATA_FAILED:"MANAGEDIT_BENEFITS_DATA_FAILED",

//MANAGEDIT INCORPORATE

MANAGEDIT_INCORPORATE_PAGE_DATA_START:"MANAGEDIT_INCORPORATE_PAGE_DATA_START",
MANAGEDIT_INCORPORATE_DATA_SUCCEEDED: "MANAGEDIT_INCORPORATE_DATA_SUCCEEDED",
MANAGEDIT_INCORPORATE_DATA_FAILED:"MANAGEDIT_INCORPORATE_DATA_FAILED",

//MANAGEDIT MANAGED
MANAGEDIT_MANAGED_PAGE_DATA_START:"MANAGEDIT_MANAGED_PAGE_DATA_START",
MANAGEDIT_MANAGED_DATA_SUCCEEDED: "MANAGEDIT_MANAGED_DATA_SUCCEEDED",
MANAGEDIT_MANAGED_DATA_FAILED:"MANAGEDIT_MANAGED_DATA_FAILED",


//MANAGEDIT SOLUTION

MANAGEDIT_SOLUTION_PAGE_DATA_START:"MANAGEDIT_SOLUTION_PAGE_DATA_START",
MANAGEDIT_SOLUTION_DATA_SUCCEEDED: "MANAGEDIT_SOLUTION_DATA_SUCCEEDED",
MANAGEDIT_SOLUTION_DATA_FAILED:"MANAGEDIT_SOLUTION_DATA_FAILED",

//MANAGEDIT UVATION

MANAGEDIT_UVATION_PAGE_DATA_START:"MANAGEDIT_UVATION_PAGE_DATA_START",
MANAGEDIT_UVATION_DATA_SUCCEEDED: "MANAGEDIT_UVATION_DATA_SUCCEEDED",
MANAGEDIT_UVATION_DATA_FAILED:"MANAGEDIT_UVATION_DATA_FAILED",

//MANAGEDIT CHAT

MANAGEDIT_CHAT_PAGE_DATA_START:"MANAGEDIT_CHAT_PAGE_DATA_START",
MANAGEDIT_CHAT_DATA_SUCCEEDED: "MANAGEDIT_CHAT_DATA_SUCCEEDED",
MANAGEDIT_CHAT_DATA_FAILED:"MANAGEDIT_CHAT_DATA_FAILED",

//MANAGED IT PAGE ENDS

//Workforce PAGE Starts

WORKFORCE_LANDING_PAGE_DATA_START:"WORKFORCE_LANDING_PAGE_DATA_START",
WORKFORCE_LANDING_DATA_SUCCEEDED: "WORKFORCE_LANDING_DATA_SUCCEEDED",
WORKFORCE_LANDING_DATA_FAILED:"WORKFORCE_LANDING_DATA_FAILED",

//workforce approach

WORKFORCE_APPROACH_PAGE_DATA_START:"WORKFORCE_APPROACH_PAGE_DATA_START",
WORKFORCE_APPROACH_DATA_SUCCEEDED: "WORKFORCE_APPROACH_DATA_SUCCEEDED",
WORKFORCE_APPROACH_DATA_FAILED:"WORKFORCE_APPROACH_DATA_FAILED",

//workforce reachout
WORKFORCE_REACHOUT_PAGE_DATA_START:"WORKFORCE_REACHOUT_PAGE_DATA_START",
WORKFORCE_REACHOUT_DATA_SUCCEEDED: "WORKFORCE_REACHOUT_DATA_SUCCEEDED",
WORKFORCE_REACHOUT_DATA_FAILED:"WORKFORCE_REACHOUT_DATA_FAILED",

//workforce Drives
WORKFORCE_DRIVES_PAGE_DATA_START:"WORKFORCE_DRIVES_PAGE_DATA_START",
WORKFORCE_DRIVES_DATA_SUCCEEDED: "WORKFORCE_DRIVES_DATA_SUCCEEDED",
WORKFORCE_DRIVES_DATA_FAILED:"WORKFORCE_DRIVES_DATA_FAILED",

//WORKFORCE SOURCING

WORKFORCE_SOURCING_PAGE_DATA_START:"WORKFORCE_SOURCING_PAGE_DATA_START",
WORKFORCE_SOURCING_DATA_SUCCEEDED: "WORKFORCE_SOURCING_DATA_SUCCEEDED",
WORKFORCE_SOURCING_DATA_FAILED:"WORKFORCE_SOURCING_DATA_FAILED",

//WORKFORCE CHAT
WORKFORCE_CHAT_PAGE_DATA_START:"WORKFORCE_CHAT_PAGE_DATA_START",
WORKFORCE_CHAT_DATA_SUCCEEDED: "WORKFORCE_CHAT_DATA_SUCCEEDED",
WORKFORCE_CHAT_DATA_FAILED:"WORKFORCE_CHAT_DATA_FAILED",


//Workforce PAGE Ends

//CYBERSECURITY PAGE STARTS

//CYBERSECURITY LANDING

CYBERSECURITY_LANDING_PAGE_DATA_START:"CYBERSECURITY_LANDING_PAGE_DATA_START",
CYBERSECURITY_LANDING_DATA_SUCCEEDED: "CYBERSECURITY_LANDING_DATA_SUCCEEDED",
CYBERSECURITY_LANDING_DATA_FAILED:"CYBERSECURITY_LANDING_DATA_FAILED",

//CYBERSECURITYCHAT

CYBERSECURITY_CHAT_PAGE_DATA_START:"CYBERSECURITY_CHAT_PAGE_DATA_START",
CYBERSECURITY_CHAT_DATA_SUCCEEDED: "CYBERSECURITY_CHAT_DATA_SUCCEEDED",
CYBERSECURITY_CHAT_DATA_FAILED:"CYBERSECURITY_CHAT_DATA_FAILED",

//CYBERSECURITY PAGE ENDS

// SOC PAGE STARTS

//SOC LANDING PAGE

SOC_LANDING_PAGE_DATA_START:"SOC_LANDING_PAGE_DATA_START",
SOC_LANDING_DATA_SUCCEEDED: "SOC_LANDING_DATA_SUCCEEDED",
SOC_LANDING_DATA_FAILED:"SOC_LANDING_DATA_FAILED",



//SOC PAGE ENDS

}



export default actionTypes;